# Site settings 按照自己的网站信息做点修改
title: flyzy小站
SEOTitle: flyzy小站 | flyzy小站，GitHub Pages分部
header-img: img/home-bg.jpg
email: flyzy2005@gmail.com
description: "flyzy小站GitHub分站~"
keyword: "技术分享,科学上网,建站教程"
url: "https://flyzy2005.github.io"              # your host, for absolute URL
baseurl: ""         # 例如, '/blog' 如果你的博客的路径是'host/blog'，默认是空



# SNS settings 就是关于我下面的图标，不需要注释即可~需要就填自己的用户名
RSS: false
csdn_username: wf632856695
#weibo_username:     flyzy2005
#zhihu_username:     flyzy2005
github_username:    flyzy2005
#twitter_username:  flyzy2005
#facebook_username:  flyzy2005



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings 不用请注释这两行！！！
# Baidu 统计 （自己百度搜索百度统计获得自己的追踪代码）
ba_track_id: b0194eff1ffb1d6ad8b04f0440bdf507
# Google 分析 （登录需要要翻墙，不需要的请注释下面一行，请一定要注释啊，不然记录全跑我那里了！！！）
ga_track_id: 'UA-112052918-2'            # 格式: UA-xxxxxx-xx



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "学习ing~</br>主页：<a href=\"https://www.flyzy2005.cn\">flyzy小站</a>" # 关于我的介绍
sidebar-avatar: /img/avatar.jpg      # 头像图片，在首页、关于我、标签聚合里用到



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends 友链~留着我的友链那就太好了-。-
friends: [
    {
        title: "flyzy小站",
        href: "https://www.flyzy2005.cn",
        description: "flyzy小站总部，欢迎来给我留言~"
    }
]
